name: Run tox with multiple Python versions

on: [push, pull_request]

jobs:
  tox:
    name: Run tox
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.8, 3.7, 3.6]
    steps:
      - name: Checkout dialogflow-fulfillment
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Update pip
        run: python -m pip install -U pip
      - name: Install tox
        run: pip install tox
      - name: Run tox
        run: tox
